/* plugin_exchange.c -- generated by Trunnel v1.5.3.
 * https://gitweb.torproject.org/trunnel.git
 * You probably shouldn't edit this file.
 */
#include <stdlib.h>
#include "trunnel-impl.h"

#include "plugin_exchange.h"

#define TRUNNEL_SET_ERROR_CODE(obj) \
  do {                              \
    (obj)->trunnel_error_code_ = 1; \
  } while (0)

#if defined(__COVERITY__) || defined(__clang_analyzer__)
/* If we're running a static analysis tool, we don't want it to complain
 * that some of our remaining-bytes checks are dead-code. */
int pluginexchange_deadcode_dummy__ = 0;
#define OR_DEADCODE_DUMMY || pluginexchange_deadcode_dummy__
#else
#define OR_DEADCODE_DUMMY
#endif

#define CHECK_REMAINING(nbytes, label)                           \
  do {                                                           \
    if (remaining < (nbytes) OR_DEADCODE_DUMMY) {                \
      goto label;                                                \
    }                                                            \
  } while (0)

plugin_file_part_t *
plugin_file_part_new(void)
{
  plugin_file_part_t *val = trunnel_calloc(1, sizeof(plugin_file_part_t));
  if (NULL == val)
    return NULL;
  return val;
}

/** Release all storage held inside 'obj', but do not free 'obj'.
 */
static void
plugin_file_part_clear(plugin_file_part_t *obj)
{
  (void) obj;
  TRUNNEL_DYNARRAY_WIPE(&obj->file_name);
  TRUNNEL_DYNARRAY_CLEAR(&obj->file_name);
  TRUNNEL_DYNARRAY_WIPE(&obj->data);
  TRUNNEL_DYNARRAY_CLEAR(&obj->data);
}

void
plugin_file_part_free(plugin_file_part_t *obj)
{
  if (obj == NULL)
    return;
  plugin_file_part_clear(obj);
  trunnel_memwipe(obj, sizeof(plugin_file_part_t));
  trunnel_free_(obj);
}

uint16_t
plugin_file_part_get_file_name_len(const plugin_file_part_t *inp)
{
  return inp->file_name_len;
}
int
plugin_file_part_set_file_name_len(plugin_file_part_t *inp, uint16_t val)
{
  inp->file_name_len = val;
  return 0;
}
uint16_t
plugin_file_part_get_data_len(const plugin_file_part_t *inp)
{
  return inp->data_len;
}
int
plugin_file_part_set_data_len(plugin_file_part_t *inp, uint16_t val)
{
  inp->data_len = val;
  return 0;
}
uint8_t
plugin_file_part_get_is_last_chunk(const plugin_file_part_t *inp)
{
  return inp->is_last_chunk;
}
int
plugin_file_part_set_is_last_chunk(plugin_file_part_t *inp, uint8_t val)
{
  if (! ((val == 0 || val == 1))) {
     TRUNNEL_SET_ERROR_CODE(inp);
     return -1;
  }
  inp->is_last_chunk = val;
  return 0;
}
size_t
plugin_file_part_getlen_file_name(const plugin_file_part_t *inp)
{
  return TRUNNEL_DYNARRAY_LEN(&inp->file_name);
}

uint8_t
plugin_file_part_get_file_name(plugin_file_part_t *inp, size_t idx)
{
  return TRUNNEL_DYNARRAY_GET(&inp->file_name, idx);
}

uint8_t
plugin_file_part_getconst_file_name(const plugin_file_part_t *inp, size_t idx)
{
  return plugin_file_part_get_file_name((plugin_file_part_t*)inp, idx);
}
int
plugin_file_part_set_file_name(plugin_file_part_t *inp, size_t idx, uint8_t elt)
{
  TRUNNEL_DYNARRAY_SET(&inp->file_name, idx, elt);
  return 0;
}
int
plugin_file_part_add_file_name(plugin_file_part_t *inp, uint8_t elt)
{
#if SIZE_MAX >= UINT16_MAX
  if (inp->file_name.n_ == UINT16_MAX)
    goto trunnel_alloc_failed;
#endif
  TRUNNEL_DYNARRAY_ADD(uint8_t, &inp->file_name, elt, {});
  return 0;
 trunnel_alloc_failed:
  TRUNNEL_SET_ERROR_CODE(inp);
  return -1;
}

uint8_t *
plugin_file_part_getarray_file_name(plugin_file_part_t *inp)
{
  return inp->file_name.elts_;
}
const uint8_t  *
plugin_file_part_getconstarray_file_name(const plugin_file_part_t *inp)
{
  return (const uint8_t  *)plugin_file_part_getarray_file_name((plugin_file_part_t*)inp);
}
int
plugin_file_part_setlen_file_name(plugin_file_part_t *inp, size_t newlen)
{
  uint8_t *newptr;
#if UINT16_MAX < SIZE_MAX
  if (newlen > UINT16_MAX)
    goto trunnel_alloc_failed;
#endif
  newptr = trunnel_dynarray_setlen(&inp->file_name.allocated_,
                 &inp->file_name.n_, inp->file_name.elts_, newlen,
                 sizeof(inp->file_name.elts_[0]), (trunnel_free_fn_t) NULL,
                 &inp->trunnel_error_code_);
  if (newlen != 0 && newptr == NULL)
    goto trunnel_alloc_failed;
  inp->file_name.elts_ = newptr;
  return 0;
 trunnel_alloc_failed:
  TRUNNEL_SET_ERROR_CODE(inp);
  return -1;
}
size_t
plugin_file_part_getlen_data(const plugin_file_part_t *inp)
{
  return TRUNNEL_DYNARRAY_LEN(&inp->data);
}

uint8_t
plugin_file_part_get_data(plugin_file_part_t *inp, size_t idx)
{
  return TRUNNEL_DYNARRAY_GET(&inp->data, idx);
}

uint8_t
plugin_file_part_getconst_data(const plugin_file_part_t *inp, size_t idx)
{
  return plugin_file_part_get_data((plugin_file_part_t*)inp, idx);
}
int
plugin_file_part_set_data(plugin_file_part_t *inp, size_t idx, uint8_t elt)
{
  TRUNNEL_DYNARRAY_SET(&inp->data, idx, elt);
  return 0;
}
int
plugin_file_part_add_data(plugin_file_part_t *inp, uint8_t elt)
{
#if SIZE_MAX >= UINT16_MAX
  if (inp->data.n_ == UINT16_MAX)
    goto trunnel_alloc_failed;
#endif
  TRUNNEL_DYNARRAY_ADD(uint8_t, &inp->data, elt, {});
  return 0;
 trunnel_alloc_failed:
  TRUNNEL_SET_ERROR_CODE(inp);
  return -1;
}

uint8_t *
plugin_file_part_getarray_data(plugin_file_part_t *inp)
{
  return inp->data.elts_;
}
const uint8_t  *
plugin_file_part_getconstarray_data(const plugin_file_part_t *inp)
{
  return (const uint8_t  *)plugin_file_part_getarray_data((plugin_file_part_t*)inp);
}
int
plugin_file_part_setlen_data(plugin_file_part_t *inp, size_t newlen)
{
  uint8_t *newptr;
#if UINT16_MAX < SIZE_MAX
  if (newlen > UINT16_MAX)
    goto trunnel_alloc_failed;
#endif
  newptr = trunnel_dynarray_setlen(&inp->data.allocated_,
                 &inp->data.n_, inp->data.elts_, newlen,
                 sizeof(inp->data.elts_[0]), (trunnel_free_fn_t) NULL,
                 &inp->trunnel_error_code_);
  if (newlen != 0 && newptr == NULL)
    goto trunnel_alloc_failed;
  inp->data.elts_ = newptr;
  return 0;
 trunnel_alloc_failed:
  TRUNNEL_SET_ERROR_CODE(inp);
  return -1;
}
const char *
plugin_file_part_check(const plugin_file_part_t *obj)
{
  if (obj == NULL)
    return "Object was NULL";
  if (obj->trunnel_error_code_)
    return "A set function failed on this object";
  if (! (obj->is_last_chunk == 0 || obj->is_last_chunk == 1))
    return "Integer out of bounds";
  if (TRUNNEL_DYNARRAY_LEN(&obj->file_name) != obj->file_name_len)
    return "Length mismatch for file_name";
  if (TRUNNEL_DYNARRAY_LEN(&obj->data) != obj->data_len)
    return "Length mismatch for data";
  return NULL;
}

ssize_t
plugin_file_part_encoded_len(const plugin_file_part_t *obj)
{
  ssize_t result = 0;

  if (NULL != plugin_file_part_check(obj))
     return -1;


  /* Length of u16 file_name_len */
  result += 2;

  /* Length of u16 data_len */
  result += 2;

  /* Length of u8 is_last_chunk IN [0, 1] */
  result += 1;

  /* Length of u8 file_name[file_name_len] */
  result += TRUNNEL_DYNARRAY_LEN(&obj->file_name);

  /* Length of u8 data[data_len] */
  result += TRUNNEL_DYNARRAY_LEN(&obj->data);
  return result;
}
int
plugin_file_part_clear_errors(plugin_file_part_t *obj)
{
  int r = obj->trunnel_error_code_;
  obj->trunnel_error_code_ = 0;
  return r;
}
ssize_t
plugin_file_part_encode(uint8_t *output, const size_t avail, const plugin_file_part_t *obj)
{
  ssize_t result = 0;
  size_t written = 0;
  uint8_t *ptr = output;
  const char *msg;
#ifdef TRUNNEL_CHECK_ENCODED_LEN
  const ssize_t encoded_len = plugin_file_part_encoded_len(obj);
#endif

  if (NULL != (msg = plugin_file_part_check(obj)))
    goto check_failed;

#ifdef TRUNNEL_CHECK_ENCODED_LEN
  trunnel_assert(encoded_len >= 0);
#endif

  /* Encode u16 file_name_len */
  trunnel_assert(written <= avail);
  if (avail - written < 2)
    goto truncated;
  trunnel_set_uint16(ptr, trunnel_htons(obj->file_name_len));
  written += 2; ptr += 2;

  /* Encode u16 data_len */
  trunnel_assert(written <= avail);
  if (avail - written < 2)
    goto truncated;
  trunnel_set_uint16(ptr, trunnel_htons(obj->data_len));
  written += 2; ptr += 2;

  /* Encode u8 is_last_chunk IN [0, 1] */
  trunnel_assert(written <= avail);
  if (avail - written < 1)
    goto truncated;
  trunnel_set_uint8(ptr, (obj->is_last_chunk));
  written += 1; ptr += 1;

  /* Encode u8 file_name[file_name_len] */
  {
    size_t elt_len = TRUNNEL_DYNARRAY_LEN(&obj->file_name);
    trunnel_assert(obj->file_name_len == elt_len);
    trunnel_assert(written <= avail);
    if (avail - written < elt_len)
      goto truncated;
    if (elt_len)
      memcpy(ptr, obj->file_name.elts_, elt_len);
    written += elt_len; ptr += elt_len;
  }

  /* Encode u8 data[data_len] */
  {
    size_t elt_len = TRUNNEL_DYNARRAY_LEN(&obj->data);
    trunnel_assert(obj->data_len == elt_len);
    trunnel_assert(written <= avail);
    if (avail - written < elt_len)
      goto truncated;
    if (elt_len)
      memcpy(ptr, obj->data.elts_, elt_len);
    written += elt_len; ptr += elt_len;
  }


  trunnel_assert(ptr == output + written);
#ifdef TRUNNEL_CHECK_ENCODED_LEN
  {
    trunnel_assert(encoded_len >= 0);
    trunnel_assert((size_t)encoded_len == written);
  }

#endif

  return written;

 truncated:
  result = -2;
  goto fail;
 check_failed:
  (void)msg;
  result = -1;
  goto fail;
 fail:
  trunnel_assert(result < 0);
  return result;
}

/** As plugin_file_part_parse(), but do not allocate the output
 * object.
 */
static ssize_t
plugin_file_part_parse_into(plugin_file_part_t *obj, const uint8_t *input, const size_t len_in)
{
  const uint8_t *ptr = input;
  size_t remaining = len_in;
  ssize_t result = 0;
  (void)result;

  /* Parse u16 file_name_len */
  CHECK_REMAINING(2, truncated);
  obj->file_name_len = trunnel_ntohs(trunnel_get_uint16(ptr));
  remaining -= 2; ptr += 2;

  /* Parse u16 data_len */
  CHECK_REMAINING(2, truncated);
  obj->data_len = trunnel_ntohs(trunnel_get_uint16(ptr));
  remaining -= 2; ptr += 2;

  /* Parse u8 is_last_chunk IN [0, 1] */
  CHECK_REMAINING(1, truncated);
  obj->is_last_chunk = (trunnel_get_uint8(ptr));
  remaining -= 1; ptr += 1;
  if (! (obj->is_last_chunk == 0 || obj->is_last_chunk == 1))
    goto fail;

  /* Parse u8 file_name[file_name_len] */
  CHECK_REMAINING(obj->file_name_len, truncated);
  TRUNNEL_DYNARRAY_EXPAND(uint8_t, &obj->file_name, obj->file_name_len, {});
  obj->file_name.n_ = obj->file_name_len;
  if (obj->file_name_len)
    memcpy(obj->file_name.elts_, ptr, obj->file_name_len);
  ptr += obj->file_name_len; remaining -= obj->file_name_len;

  /* Parse u8 data[data_len] */
  CHECK_REMAINING(obj->data_len, truncated);
  TRUNNEL_DYNARRAY_EXPAND(uint8_t, &obj->data, obj->data_len, {});
  obj->data.n_ = obj->data_len;
  if (obj->data_len)
    memcpy(obj->data.elts_, ptr, obj->data_len);
  ptr += obj->data_len; remaining -= obj->data_len;
  trunnel_assert(ptr + remaining == input + len_in);
  return len_in - remaining;

 truncated:
  return -2;
 trunnel_alloc_failed:
  return -1;
 fail:
  result = -1;
  return result;
}

ssize_t
plugin_file_part_parse(plugin_file_part_t **output, const uint8_t *input, const size_t len_in)
{
  ssize_t result;
  *output = plugin_file_part_new();
  if (NULL == *output)
    return -1;
  result = plugin_file_part_parse_into(*output, input, len_in);
  if (result < 0) {
    plugin_file_part_free(*output);
    *output = NULL;
  }
  return result;
}
