/* circpad_dropmark_plugin.c -- generated by Trunnel v1.5.3.
 * https://gitweb.torproject.org/trunnel.git
 * You probably shouldn't edit this file.
 */
#include <stdlib.h>
#include "trunnel-impl.h"

#include "circpad_dropmark_plugin.h"


#if defined(__COVERITY__) || defined(__clang_analyzer__)
/* If we're running a static analysis tool, we don't want it to complain
 * that some of our remaining-bytes checks are dead-code. */
int circpaddropmarkplugin_deadcode_dummy__ = 0;
#define OR_DEADCODE_DUMMY || circpaddropmarkplugin_deadcode_dummy__
#else
#define OR_DEADCODE_DUMMY
#endif


circpad_plugin_transition_t *
circpad_plugin_transition_new(void)
{
  circpad_plugin_transition_t *val = trunnel_calloc(1, sizeof(circpad_plugin_transition_t));
  if (NULL == val)
    return NULL;
  val->command = CIRCPAD_COMMAND_SIGPLUGIN;
  val->signal_type = CIRCPAD_SIGPLUGIN_ACTIVATE;
  return val;
}

/** Release all storage held inside 'obj', but do not free 'obj'.
 */
static void
circpad_plugin_transition_clear(circpad_plugin_transition_t *obj)
{
  (void) obj;
}

void
circpad_plugin_transition_free(circpad_plugin_transition_t *obj)
{
  if (obj == NULL)
    return;
  circpad_plugin_transition_clear(obj);
  trunnel_memwipe(obj, sizeof(circpad_plugin_transition_t));
  trunnel_free_(obj);
}

uint8_t
circpad_plugin_transition_get_command(const circpad_plugin_transition_t *inp)
{
  return inp->command;
}
int
circpad_plugin_transition_set_command(circpad_plugin_transition_t *inp, uint8_t val)
{
  if (! ((val == CIRCPAD_COMMAND_SIGPLUGIN))) {
     TRUNNEL_SET_ERROR_CODE(inp);
     return -1;
  }
  inp->command = val;
  return 0;
}
uint8_t
circpad_plugin_transition_get_signal_type(const circpad_plugin_transition_t *inp)
{
  return inp->signal_type;
}
int
circpad_plugin_transition_set_signal_type(circpad_plugin_transition_t *inp, uint8_t val)
{
  if (! ((val == CIRCPAD_SIGPLUGIN_ACTIVATE || val == CIRCPAD_SIGPLUGIN_BE_SILENT || val == CIRCPAD_SIGPLUGIN_CLOSE))) {
     TRUNNEL_SET_ERROR_CODE(inp);
     return -1;
  }
  inp->signal_type = val;
  return 0;
}
uint32_t
circpad_plugin_transition_get_machine_ctr(const circpad_plugin_transition_t *inp)
{
  return inp->machine_ctr;
}
int
circpad_plugin_transition_set_machine_ctr(circpad_plugin_transition_t *inp, uint32_t val)
{
  inp->machine_ctr = val;
  return 0;
}

int
circpad_plugin_transition_clear_errors(circpad_plugin_transition_t *obj)
{
  int r = obj->trunnel_error_code_;
  obj->trunnel_error_code_ = 0;
  return r;
}

